version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: rec_2024
    networks:
      - my_network

  web:
    build: .
    command: bash -c "rails db:prepare && rails s -b 0.0.0.0"
    depends_on: 
      - db
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - my_network

networks:
  my_network:
   driver: bridge